services:
  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: piyolog
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: "Asia/Tokyo"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana_storage:/var/lib/grafana
  retriever:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: retriever
    restart: always
  pic_server:
    build:
      context: ./grafana_pic_server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"

volumes:
  db_data:
  grafana_storage:
