{
 "title": "成長記録",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  { "title": "各種メトリック", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "経過時間(時間)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT \r\n  day_record_date, \r\n  TIME_TO_SEC(TIMEDIFF(now(),day_record_date)) / 60 / 60 AS DIFF_MIN_MILK,\r\n  record_type \r\nFROM piyolog.records \r\nWHERE record_type = 'ミルク' \r\nORDER BY day_record_date DESC \r\nLIMIT 1\r\n"
    },
    {
     "dataset": "piyolog",
     "rawSql": "\r\nSELECT \r\n  day_record_date, \r\n  TIME_TO_SEC(TIMEDIFF(now(),day_record_date)) / 60 / 60 AS DIFF_MIN_DIAPER,\r\n  record_type \r\nFROM piyolog.records \r\nWHERE record_type = 'うんち' or record_type = 'おしっこ'\r\nORDER BY day_record_date DESC \r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "ぴよログ入力内容",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 1 },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT \r\n  day_record_date, \r\n  CONCAT(record_type,IF(additional_record_data <> '',CONCAT(\"(\",additional_record_data,\")\"),\"\")) AS record_type, \r\n  record_memo\r\nFROM piyolog.records \r\nWHERE day_record_date <= now()\r\nORDER BY day_record_date DESC \r\nLIMIT 30 "
    }
   ]
  },
  {
   "title": "睡眠時間",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT id, date FROM piyolog.day_record ORDER BY id DESC LIMIT 1000 "
    },
    {
     "dataset": "piyolog",
     "rawSql": "SELECT day_record_id AS \"id\", sleep_duration_seconds FROM piyolog.day_record_summary LIMIT 1000 "
    }
   ]
  },
  {
   "title": "これからの予定",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 9 },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT \r\n  day_record_date, \r\n  CONCAT(record_type,IF(additional_record_data <> '',CONCAT(\"(\",additional_record_data,\")\"),\"\")) AS record_type, \r\n  record_memo\r\nFROM piyolog.records \r\nWHERE day_record_date > now()\r\nORDER BY day_record_date DESC \r\nLIMIT 30"
    }
   ]
  },
  { "title": "統計", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "うんち・おしっこカウント",
   "type": "timeseries",
   "description": "日別の回数グラフ",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 18 },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT day_record_id AS \"id\", pee_count, poo_count FROM piyolog.day_record_summary LIMIT 1000 "
    },
    {
     "dataset": "piyolog",
     "rawSql": "SELECT date, id FROM piyolog.day_record ORDER BY date DESC LIMIT 1000 "
    }
   ]
  },
  {
   "title": "ミルク量",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 18 },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT formula_total_amount, day_record_id AS \"id\" FROM piyolog.day_record_summary LIMIT 50 "
    },
    {
     "dataset": "piyolog",
     "rawSql": "SELECT id, date FROM piyolog.day_record LIMIT 50 "
    }
   ]
  },
  {
   "title": "最終おむつからの経過時間(時間)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT \r\n  day_record_date, \r\n  TIME_TO_SEC(TIMEDIFF(now(),day_record_date)) / 60 / 60 AS DIFF_HOUR,\r\n  record_type \r\nFROM piyolog.records \r\nWHERE record_type = 'うんち' or record_type = 'おしっこ'\r\nORDER BY day_record_date DESC \r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "最終ミルクからの経過時間(時間)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT \r\n  day_record_date, \r\n  TIME_TO_SEC(TIMEDIFF(now(),day_record_date)) / 60 / 60 AS DIFF_MIN,\r\n  record_type \r\nFROM piyolog.records \r\nWHERE record_type = 'ミルク' \r\nORDER BY day_record_date DESC \r\nLIMIT 1"
    }
   ]
  },
  { "title": "ぴよログ", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "日記",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "piyolog",
     "rawSql": "SELECT date AS '日付', daily_memo AS '日記' FROM piyolog.day_record WHERE date <= now() ORDER BY date DESC LIMIT 10 "
    }
   ]
  }
 ]
}